# Created using wingetcreate

PackageIdentifier: Irium.Webcam
PackageVersion: 2.6.6
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://1758658189.rsc.cdn77.org/WinWebcam-2.6.6.exe
  InstallerSha256: 842D0BB023F01AF4B4008E36D16EC3491915FFF884DAEE9AAF9A62CEDEE2ABDC
ManifestType: installer
ManifestVersion: 1.0.0
